### ISSUE TITLE
Enhance Repository for more collaborative development.

### ISSUE THREAD

**Issue by adityabhattad2021** [StabilityNexus/FairFund#25]
To facilitate a smooth collaborative development process, we need to implement some basic checks and templates for pull requests and issues, along with a simple CI/CD flow.
## Tasks (tentative):
- Create a basic PR template with sections for description, changes made, and testing done.
- Set up a GitHub Actions workflow to:
   1. Run tests on every pull request
   2. Perform basic linting checks
   3. Ensure the frontend builds successfully
 
- Add a simple issue template for bug reports and feature requests.
- Make README.md more extensive

**Comment by Alokih** [comment]
Hey @adityabhattad2021 Can I try this issue ?

**Comment by adityabhattad2021** [comment]
> Hey @adityabhattad2021 Can I try this issue ?
Actually this issue should have already been closed, as I have updated the readme recently and also added pre commit hooks for linting.

**Comment by Alokih** [comment]
Ok @adityabhattad2021
