### ISSUE TITLE
fix:add css to remove scrollbar

### ISSUE THREAD

**Issue by ShivamBisen** [StabilityNexus/FairFund#49]
The scrollbar appears only when necessary. While the scrollbar is present on the initial dashboard page, there is an odd transition of the navigation bar adjustment when navigating to the spaces page. This creates an inconsistent user experience.

dashboard : 
[
![Screenshot_2024-10-08_14_14_55](https://github.com/user-attachments/assets/f8566f1d-aa01-4e3c-b35f-669f03ec39da)
](url)

![Screenshot_2024-10-08_14_15_01](https://github.com/user-attachments/assets/0dd170f1-3b98-4878-9e99-bc6da4fc7b77)

**Comment by adityabhattad2021** [comment]
Merged!
